# Generated by Django 5.2.3 on 2025-07-12 13:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coin_is_active_alter_coin_ath_alter_coin_atl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=20),
        ),
    ]
