# Generated by Django 5.2.3 on 2025-07-22 07:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'انجام شده'), ('failed', 'ناموفق')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0.0'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.coin'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0'), max_digits=30),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
