# Generated by Django 5.2.3 on 2025-07-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction_status_alter_asset_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='amount',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
